name: Create tag based on crate version

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: metadata
        
    - name: Get current crate version
      id: crateVersion
      # Command to run
      run: echo "cargo_version=$(cargo-metadata --format-version 1 | jq '.packages[] | select(.name == "discord-rpc-helper") | .version')" >> $GITHUB_OUTPUT
      
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ github.token }}
        custom_tag: ${{ steps.crateVersion.outputs.stdout }}
